module.exports = unifiedAbsenceArray = [
    {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '16/08/2018',
        startTime: '08:30',
        endDate: '16/08/2018',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 7, 30 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sun',
        startDayOfTheMonth: 16,
        startMonth: 'Sep',
        startMonthNumber: 8,
        startYear: 2018,
        brhrStartDate: 'Sun 16 Sep 2018',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 16,
        endMonth: 'Sep',
        endMonthNumber: 8,
        endYear: 2018,
        brhrEndDate: 'Sun 16 Sep 2018',
        startHour: 8,
        startMinutes: 30,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '18/09/2018',
        startTime: '08:30',
        endDate: '18/09/2018',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 37, 30 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 18,
        startMonth: 'Oct',
        startMonthNumber: 9,
        startYear: 2018,
        brhrStartDate: 'Thu 18 Oct 2018',
        endDayOfTheWeek: 'Thu',
        endDayOfTheMonth: 18,
        endMonth: 'Oct',
        endMonthNumber: 9,
        endYear: 2018,
        brhrEndDate: 'Thu 18 Oct 2018',
        startHour: 8,
        startMinutes: 30,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '25/09/2018',
        startTime: '09:00',
        endDate: '01/01/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 1536, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 25,
        startMonth: 'Oct',
        startMonthNumber: 9,
        startYear: 2018,
        brhrStartDate: 'Thu 25 Oct 2018',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 1,
        endMonth: 'Feb',
        endMonthNumber: 1,
        endYear: 2019,
        brhrEndDate: 'Fri 01 Feb 2019',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/11/2018',
        startTime: '09:00',
        endDate: '05/11/2018',
        endTime: '16:00',
        durationInDays: null,
        durationInHours: [ 18, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Wed',
        startDayOfTheMonth: 5,
        startMonth: 'Dec',
        startMonthNumber: 11,
        startYear: 2018,
        brhrStartDate: 'Wed 05 Dec 2018',
        endDayOfTheWeek: 'Wed',
        endDayOfTheMonth: 5,
        endMonth: 'Dec',
        endMonthNumber: 11,
        endYear: 2018,
        brhrEndDate: 'Wed 05 Dec 2018',
        startHour: 9,
        startMinutes: 0,
        endHour: 16,
        endMinutes: 0
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '14/11/2018',
        startTime: '08:30',
        endDate: '23/11/2018',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Fri',
        startDayOfTheMonth: 14,
        startMonth: 'Dec',
        startMonthNumber: 11,
        startYear: 2018,
        brhrStartDate: 'Fri 14 Dec 2018',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 23,
        endMonth: 'Dec',
        endMonthNumber: 11,
        endYear: 2018,
        brhrEndDate: 'Sun 23 Dec 2018',
        startHour: 8,
        startMinutes: 30,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/03/2019',
        startTime: '09:00',
        endDate: '12/03/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 96, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: 'Poorly with flu symptoms',
        startDayOfTheWeek: 'Fri',
        startDayOfTheMonth: 5,
        startMonth: 'Apr',
        startMonthNumber: 3,
        startYear: 2019,
        brhrStartDate: 'Fri 05 Apr 2019',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 12,
        endMonth: 'Apr',
        endMonthNumber: 3,
        endYear: 2019,
        brhrEndDate: 'Fri 12 Apr 2019',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '24/06/2019',
        startTime: '00:00',
        endDate: '27/06/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Wed',
        startDayOfTheMonth: 24,
        startMonth: 'Jul',
        startMonthNumber: 6,
        startYear: 2019,
        brhrStartDate: 'Wed 24 Jul 2019',
        endDayOfTheWeek: 'Sat',
        endDayOfTheMonth: 27,
        endMonth: 'Jul',
        endMonthNumber: 6,
        endYear: 2019,
        brhrEndDate: 'Sat 27 Jul 2019',
        startHour: 0,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Other',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '04/07/2019',
        startTime: '08:30',
        endDate: '04/07/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 7, 30 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sun',
        startDayOfTheMonth: 4,
        startMonth: 'Aug',
        startMonthNumber: 7,
        startYear: 2019,
        brhrStartDate: 'Sun 04 Aug 2019',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 4,
        endMonth: 'Aug',
        endMonthNumber: 7,
        endYear: 2019,
        brhrEndDate: 'Sun 04 Aug 2019',
        startHour: 8,
        startMinutes: 30,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '12/07/2019',
        startTime: '08:30',
        endDate: '12/07/2019',
        endTime: '12:00',
        durationInDays: null,
        durationInHours: [ 3, 45 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Mon',
        startDayOfTheMonth: 12,
        startMonth: 'Aug',
        startMonthNumber: 7,
        startYear: 2019,
        brhrStartDate: 'Mon 12 Aug 2019',
        endDayOfTheWeek: 'Mon',
        endDayOfTheMonth: 12,
        endMonth: 'Aug',
        endMonthNumber: 7,
        endYear: 2019,
        brhrEndDate: 'Mon 12 Aug 2019',
        startHour: 8,
        startMinutes: 30,
        endHour: 12,
        endMinutes: 0
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Unpaid leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '12/07/2019',
        startTime: '12:05',
        endDate: '12/07/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 3, 45 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Mon',
        startDayOfTheMonth: 12,
        startMonth: 'Aug',
        startMonthNumber: 7,
        startYear: 2019,
        brhrStartDate: 'Mon 12 Aug 2019',
        endDayOfTheWeek: 'Mon',
        endDayOfTheMonth: 12,
        endMonth: 'Aug',
        endMonthNumber: 7,
        endYear: 2019,
        brhrEndDate: 'Mon 12 Aug 2019',
        startHour: 12,
        startMinutes: 5,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Other',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/09/2019',
        startTime: '08:30',
        endDate: '05/09/2019',
        endTime: '10:30',
        durationInDays: null,
        durationInHours: [ 1, 52 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sat',
        startDayOfTheMonth: 5,
        startMonth: 'Oct',
        startMonthNumber: 9,
        startYear: 2019,
        brhrStartDate: 'Sat 05 Oct 2019',
        endDayOfTheWeek: 'Sat',
        endDayOfTheMonth: 5,
        endMonth: 'Oct',
        endMonthNumber: 9,
        endYear: 2019,
        brhrEndDate: 'Sat 05 Oct 2019',
        startHour: 8,
        startMinutes: 30,
        endHour: 10,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/09/2019',
        startTime: '10:35',
        endDate: '05/09/2019',
        endTime: '12:30',
        durationInDays: null,
        durationInHours: [ 1, 52 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sat',
        startDayOfTheMonth: 5,
        startMonth: 'Oct',
        startMonthNumber: 9,
        startYear: 2019,
        brhrStartDate: 'Sat 05 Oct 2019',
        endDayOfTheWeek: 'Sat',
        endDayOfTheMonth: 5,
        endMonth: 'Oct',
        endMonthNumber: 9,
        endYear: 2019,
        brhrEndDate: 'Sat 05 Oct 2019',
        startHour: 10,
        startMinutes: 35,
        endHour: 12,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Other',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/09/2019',
        startTime: '12:35',
        endDate: '05/09/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 3, 45 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sat',
        startDayOfTheMonth: 5,
        startMonth: 'Oct',
        startMonthNumber: 9,
        startYear: 2019,
        brhrStartDate: 'Sat 05 Oct 2019',
        endDayOfTheWeek: 'Sat',
        endDayOfTheMonth: 5,
        endMonth: 'Oct',
        endMonthNumber: 9,
        endYear: 2019,
        brhrEndDate: 'Sat 05 Oct 2019',
        startHour: 12,
        startMinutes: 35,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '31/10/2019',
        startTime: '08:30',
        endDate: '31/10/2019',
        endTime: '17:30',
        durationInDays: null,
        durationInHours: [ 7, 30 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sun',
        startDayOfTheMonth: 31,
        startMonth: 'Dec',
        startMonthNumber: 10,
        startYear: 2019,
        brhrStartDate: 'Sun 31 Dec 2019',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 31,
        endMonth: 'Dec',
        endMonthNumber: 10,
        endYear: 2019,
        brhrEndDate: 'Sun 31 Dec 2019',
        startHour: 8,
        startMinutes: 30,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '09/04/2020',
        startTime: '08:30',
        endDate: '15/04/2020',
        endTime: '00:00',
        durationInDays: null,
        durationInHours: [ 32, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sat',
        startDayOfTheMonth: 9,
        startMonth: 'May',
        startMonthNumber: 4,
        startYear: 2020,
        brhrStartDate: 'Sat 09 May 2020',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 15,
        endMonth: 'May',
        endMonthNumber: 4,
        endYear: 2020,
        brhrEndDate: 'Fri 15 May 2020',
        startHour: 8,
        startMinutes: 30,
        endHour: 0,
        endMinutes: 0
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/05/2020',
        startTime: '00:00',
        endDate: '20/05/2020',
        endTime: '00:00',
        durationInDays: null,
        durationInHours: [ 64, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Fri',
        startDayOfTheMonth: 5,
        startMonth: 'Jun',
        startMonthNumber: 5,
        startYear: 2020,
        brhrStartDate: 'Fri 05 Jun 2020',
        endDayOfTheWeek: 'Sat',
        endDayOfTheMonth: 20,
        endMonth: 'Jun',
        endMonthNumber: 5,
        endYear: 2020,
        brhrEndDate: 'Sat 20 Jun 2020',
        startHour: 0,
        startMinutes: 0,
        endHour: 0,
        endMinutes: 0
      },
      {
        fullName: 'angela houghton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '09/06/2020',
        startTime: '09:00',
        endDate: '12/06/2020',
        endTime: '17:00',
        durationInDays: null,
        durationInHours: [ 15, 30 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'hours',
        brhrID: '/employee-profile/1521565/personaldetails',
        email: 'angelahoughton@brighthr.yo',
        notes: 'cds',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 9,
        startMonth: 'Jul',
        startMonthNumber: 6,
        startYear: 2020,
        brhrStartDate: 'Thu 09 Jul 2020',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 12,
        endMonth: 'Jul',
        endMonthNumber: 6,
        endYear: 2020,
        brhrEndDate: 'Sun 12 Jul 2020',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 0
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '01/10/2016',
        startTime: '00:00',
        endDate: '01/10/2016',
        endTime: '23:59',
        durationInDays: 1,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: 'newnew',
        startDayOfTheWeek: 'Tue',
        startDayOfTheMonth: 1,
        startMonth: 'Nov',
        startMonthNumber: 10,
        startYear: 2016,
        brhrStartDate: 'Tue 01 Nov 2016',
        endDayOfTheWeek: 'Tue',
        endDayOfTheMonth: 1,
        endMonth: 'Nov',
        endMonthNumber: 10,
        endYear: 2016,
        brhrEndDate: 'Tue 01 Nov 2016',
        startHour: 0,
        startMinutes: 0,
        endHour: 23,
        endMinutes: 59
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '05/06/2017',
        startTime: '09:00',
        endDate: '05/06/2017',
        endTime: '17:30',
        durationInDays: 0,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Wed',
        startDayOfTheMonth: 5,
        startMonth: 'Jul',
        startMonthNumber: 6,
        startYear: 2017,
        brhrStartDate: 'Wed 05 Jul 2017',
        endDayOfTheWeek: 'Wed',
        endDayOfTheMonth: 5,
        endMonth: 'Jul',
        endMonthNumber: 6,
        endYear: 2017,
        brhrEndDate: 'Wed 05 Jul 2017',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '06/06/2017',
        startTime: '09:00',
        endDate: '06/06/2017',
        endTime: '17:30',
        durationInDays: 1,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 6,
        startMonth: 'Jul',
        startMonthNumber: 6,
        startYear: 2017,
        brhrStartDate: 'Thu 06 Jul 2017',
        endDayOfTheWeek: 'Thu',
        endDayOfTheMonth: 6,
        endMonth: 'Jul',
        endMonthNumber: 6,
        endYear: 2017,
        brhrEndDate: 'Thu 06 Jul 2017',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '12/06/2017',
        startTime: '09:00',
        endDate: '12/06/2017',
        endTime: '17:30',
        durationInDays: 1,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Wed',
        startDayOfTheMonth: 12,
        startMonth: 'Jul',
        startMonthNumber: 6,
        startYear: 2017,
        brhrStartDate: 'Wed 12 Jul 2017',
        endDayOfTheWeek: 'Wed',
        endDayOfTheMonth: 12,
        endMonth: 'Jul',
        endMonthNumber: 6,
        endYear: 2017,
        brhrEndDate: 'Wed 12 Jul 2017',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '28/06/2017',
        startTime: '09:00',
        endDate: '28/06/2017',
        endTime: '17:30',
        durationInDays: 1,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '5uyuiu',
        startDayOfTheWeek: 'Fri',
        startDayOfTheMonth: 28,
        startMonth: 'Jul',
        startMonthNumber: 6,
        startYear: 2017,
        brhrStartDate: 'Fri 28 Jul 2017',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 28,
        endMonth: 'Jul',
        endMonthNumber: 6,
        endYear: 2017,
        brhrEndDate: 'Fri 28 Jul 2017',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '01/10/2018',
        startTime: '09:00',
        endDate: '02/10/2018',
        endTime: '17:00',
        durationInDays: 2,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 1,
        startMonth: 'Nov',
        startMonthNumber: 10,
        startYear: 2018,
        brhrStartDate: 'Thu 01 Nov 2018',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 2,
        endMonth: 'Nov',
        endMonthNumber: 10,
        endYear: 2018,
        brhrEndDate: 'Fri 02 Nov 2018',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 0
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '04/11/2019',
        startTime: '09:00',
        endDate: '12/11/2019',
        endTime: '20:57',
        durationInDays: 9,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Wed',
        startDayOfTheMonth: 4,
        startMonth: 'Dec',
        startMonthNumber: 11,
        startYear: 2019,
        brhrStartDate: 'Wed 04 Dec 2019',
        endDayOfTheWeek: 'Thu',
        endDayOfTheMonth: 12,
        endMonth: 'Dec',
        endMonthNumber: 11,
        endYear: 2019,
        brhrEndDate: 'Thu 12 Dec 2019',
        startHour: 9,
        startMinutes: 0,
        endHour: 20,
        endMinutes: 57
      },
      {
        fullName: 'ashley yarnton',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '27/08/2020',
        startTime: '09:00',
        endDate: '04/09/2020',
        endTime: '15:30',
        durationInDays: 7.5,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1521566/personaldetails',
        email: 'ashleyyarnton@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sun',
        startDayOfTheMonth: 27,
        startMonth: 'Sep',
        startMonthNumber: 8,
        startYear: 2020,
        brhrStartDate: 'Sun 27 Sep 2020',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 4,
        endMonth: 'Oct',
        endMonthNumber: 9,
        endYear: 2020,
        brhrEndDate: 'Sun 04 Oct 2020',
        startHour: 9,
        startMinutes: 0,
        endHour: 15,
        endMinutes: 30
      },
      {
        fullName: 'Guy Fawkes',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '17/10/2016',
        startTime: '09:00',
        endDate: '27/10/2016',
        endTime: '23:59',
        durationInDays: 8,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1530914/personaldetails',
        email: 'guyfawket@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 17,
        startMonth: 'Nov',
        startMonthNumber: 10,
        startYear: 2016,
        brhrStartDate: 'Thu 17 Nov 2016',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 27,
        endMonth: 'Nov',
        endMonthNumber: 10,
        endYear: 2016,
        brhrEndDate: 'Sun 27 Nov 2016',
        startHour: 9,
        startMinutes: 0,
        endHour: 23,
        endMinutes: 59
      },
      {
        fullName: 'Guy Fawkes',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '15/11/2016',
        startTime: '09:00',
        endDate: '15/11/2016',
        endTime: '17:00',
        durationInDays: 1,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1530914/personaldetails',
        email: 'guyfawket@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 15,
        startMonth: 'Dec',
        startMonthNumber: 11,
        startYear: 2016,
        brhrStartDate: 'Thu 15 Dec 2016',
        endDayOfTheWeek: 'Thu',
        endDayOfTheMonth: 15,
        endMonth: 'Dec',
        endMonthNumber: 11,
        endYear: 2016,
        brhrEndDate: 'Thu 15 Dec 2016',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 0
      },
      {
        fullName: 'Guy Fawkes',
        absenceType: 'Annual leave',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '14/12/2016',
        startTime: '08:30',
        endDate: '16/12/2016',
        endTime: '17:30',
        durationInDays: 3,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1530914/personaldetails',
        email: 'guyfawket@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Sat',
        startDayOfTheMonth: 14,
        startMonth: 'Jan',
        startMonthNumber: 12,
        startYear: 2016,
        brhrStartDate: 'Sat 14 Jan 2016',
        endDayOfTheWeek: 'Mon',
        endDayOfTheMonth: 16,
        endMonth: 'Jan',
        endMonthNumber: 12,
        endYear: 2016,
        brhrEndDate: 'Mon 16 Jan 2016',
        startHour: 8,
        startMinutes: 30,
        endHour: 17,
        endMinutes: 30
      },
      {
        fullName: 'Guy Fawkes',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '07/08/2017',
        startTime: '09:00',
        endDate: '24/08/2017',
        endTime: '17:00',
        durationInDays: 18,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1530914/personaldetails',
        email: 'guyfawket@brighthr.yo',
        notes: 'hbjbj',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 7,
        startMonth: 'Sep',
        startMonthNumber: 8,
        startYear: 2017,
        brhrStartDate: 'Thu 07 Sep 2017',
        endDayOfTheWeek: 'Sun',
        endDayOfTheMonth: 24,
        endMonth: 'Sep',
        endMonthNumber: 8,
        endYear: 2017,
        brhrEndDate: 'Sun 24 Sep 2017',
        startHour: 9,
        startMinutes: 0,
        endHour: 17,
        endMinutes: 0
      },
      {
        fullName: 'Guy Fawkes',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '01/10/2018',
        startTime: '09:00',
        endDate: '02/10/2018',
        endTime: '16:30',
        durationInDays: 1.5,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1530914/personaldetails',
        email: 'guyfawket@brighthr.yo',
        notes: 'Headache',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 1,
        startMonth: 'Nov',
        startMonthNumber: 10,
        startYear: 2018,
        brhrStartDate: 'Thu 01 Nov 2018',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 2,
        endMonth: 'Nov',
        endMonthNumber: 10,
        endYear: 2018,
        brhrEndDate: 'Fri 02 Nov 2018',
        startHour: 9,
        startMinutes: 0,
        endHour: 16,
        endMinutes: 30
      },
      {
        fullName: 'Guy Fawkes',
        absenceType: 'Sickness',
        isApproved: 'Approved',
        isOngoing: '',
        startDate: '21/02/2019',
        startTime: '09:00',
        endDate: '22/02/2019',
        endTime: '21:05',
        durationInDays: 2,
        durationInHours: [ 0, 0 ],
        employeeType: 'variable',
        holidayEntitlementUnit: 'days',
        brhrID: '/employee-profile/1530914/personaldetails',
        email: 'guyfawket@brighthr.yo',
        notes: '',
        startDayOfTheWeek: 'Thu',
        startDayOfTheMonth: 21,
        startMonth: 'Mar',
        startMonthNumber: 2,
        startYear: 2019,
        brhrStartDate: 'Thu 21 Mar 2019',
        endDayOfTheWeek: 'Fri',
        endDayOfTheMonth: 22,
        endMonth: 'Mar',
        endMonthNumber: 2,
        endYear: 2019,
        brhrEndDate: 'Fri 22 Mar 2019',
        startHour: 9,
        startMinutes: 0,
        endHour: 21,
        endMinutes: 5
      }
]